# This Docker-compose manifest will run the DATABASE ONLY at port 7200
version: '3.9'
services:
  graphdb:
    build:
      context: '.'
      dockerfile: 'licensed_graphdb.Dockerfile'
    ports:
      - '7200:7200'
    restart: always
    command: '/opt/graphdb/dist/bin/loadrdf -c /opt/graphdb/dist/conf/TK_SDG-config.ttl -m parallel /opt/graphdb/home/ontology'
