version: '3.9'
services:
  graphdb:
    extends:
      file: docker-compose-backend.yml
      service: graphdb
  api:
    depends_on: ['graphdb']
    image: fredrbus/tk_sdg_api:1.1
    ports:
      - '3001:3001'
    env_file:
      - .env
  web:
    depends_on: ['api', 'graphdb']
    extends:
      file: docker-compose-frontend.yml
      service: web
