name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Lint frontend
        run: |
          yarn
          yarn lint
        working-directory: ./frontend

      - name: Lint backend
        run: |
          yarn
          yarn lint
        working-directory: backend

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test frontend
        run: |
          yarn add eslint-plugin-react eslint-config-airbnb-typescript --save-dev 
          yarn test
        working-directory: frontend

      - name: Test backend
        run: |
          yarn
          yarn add @types/jsonwebtoken
          yarn test
        env:
          GRAPHDB_BASE_URL: http://stud211001.idi.ntnu.no:7200
          GRAPHDB_REPOSITORY: TK_SDG
          GRAPHDB_USERNAME: readAll
          GRAPHDB_PASSWORD: readAllPassword
          JWT_SECRET_TOKEN: insertsecrettokenhere
        working-directory: backend
  cypress-run:
    runs-on: ubuntu-latest
    env:
      working-directory: frontend
      REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          working-directory: frontend
          record: true
          wait-on: 'http://localhost:3000'
